Bump to ts-proto 1.165.0 to fix tsc compile error
The current version has an issue that makes it generate typescript that no longer compiles properly:

```
src/gen/google/protobuf/timestamp.ts:2:23 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.

2 import * as Long from "long";
```

This error originates from this file in ts-proto: 
https://github.com/stephenh/ts-proto/blob/v1.138.0/integration/simple/google/protobuf/timestamp.ts

And is fixed in the 1.165.0 version of the same file:
https://github.com/stephenh/ts-proto/blob/v1.165.0/integration/simple/google/protobuf/timestamp.ts